#!/usr/bin/env python3
# vim:fileencoding=utf-8
# License: GPL v3 Copyright: 2017, Kovid Goyal <kovid at kovidgoyal.net>

import ast
import atexit
import glob
import os
import re
import shlex
import shutil
import subprocess
import sys
import tempfile

# EOF_REMOTE

HOST = 'ox'

base = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(base, 'src/calibre/constants.py')) as f:
    raw = f.read()
v = re.search(r'numeric_version\s*=\s*(\(.+?\))', raw)[1]
v = '.'.join(map(str, ast.literal_eval(v)))
dmg = f'calibre-{v}.dmg'


def run(what):
    ret = subprocess.run(shlex.split(what))
    if ret.returncode != 0:
        raise SystemExit(ret.returncode)


with open(__file__, 'rb') as f:
    script = f.read().decode('utf-8')
script = script[:script.find('# EOF_REMOTE')].replace('if False:', 'if True:', 1)

with tempfile.NamedTemporaryFile(prefix='install-dmg-', suffix='.py') as f:
    cmd = './setup.py osx --dont-shutdown'
    if 'develop' in sys.argv:
        print('Disabling code-signing and notarization')
        cmd += ' --dont-sign --dont-notarize'
    run(cmd)
    f.write(script.encode('utf-8'))
    f.flush()
    run(f'scp dist/{dmg} {f.name} {HOST}:/tmp')
    run(f'ssh {HOST} python /tmp/{os.path.basename(f.name)} /tmp/{dmg}')
